config/routes.rb
Headblog::Application.routes.draw do
  get 'tags/:tag', to: 'articles#index', as: :tag
  resources :answers
  devise_for :users
  get "home/index"
  resources :comments
  resources :articles

  root :to => "home#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :published_on, :title, :user_id, :tag_list

  has_many :comments, :dependent => :destroy
  belongs_to :user

  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings

  default_scope :order => :published_on

  def author
    user.email
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).articles
  end

  def tag_list
    tags.map(&:name).join(", ")
  end
  
  def tag_list=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(:name => name.strip).first_or_create!
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new(:article_id => @article.id)
    @comment.user = current_user
 
    respond_to do |format|
      format.html # show.html.erb
      format.md { render :text => @article.body }
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new
    @article.user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    params[:article][:body] = params[:article][:body].read
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    if params[:article][:body].blank? 
      params[:article].delete(:body)
    else
      params[:article][:body] = params[:article][:body].read
    end
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def tags_for article
    content_tag :span do
      raw "Tags: " + render(article.tags).to_s + "...\n"
    end
  end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.file_field :body %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br />
    <%= f.text_field :published_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% title 'Articles' %>

<div id="tag_cloud">
  <% tag_cloud Tag.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), :class => css_class %>
  <% end %>
</div>

<div id="articles">
<% @articles.each do |article| %>
  <h2 style="inline">
    <%= link_to article.title, article %>
    <span class="comments">
      (<%= pluralize(article.comments.count, 'comment') %>)
      <%= tags_for article %>
    </span>
  </h2>
  <div class="author">
    from <%= article.author %> 
    on <%= article.published_on.strftime("%b %d, %Y") %>
  </div>
<% end %>
</div>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% title @article.title %>

<p class="author">
<em>from <%= @article.author %></em>
on <%= @article.published_on %>
</p>

<%= markdown @article.body %>

<%= tags_for @article %>

<p>
  <% if can? :edit, @article %>
    <%= link_to "Edit", edit_article_path(@article) %> |
  <% end %>
  <% if can? :destroy, @article %>
    <%= link_to "Destroy", @article, :method => :delete, :confirm => "Are you sure?" %> |
  <% end %>
  <%= link_to "Back to Articles", articles_path %>
</p>

<% unless @article.comments.empty? %>
  <h2><%= pluralize(@article.comments.size, 'comment') %></h2>

  <div id="comments">
  <% for comment in @article.comments %>
    <div class="comment">
      <strong><%= comment.author %></strong>
      <em>on <%= comment.created_at.strftime('%b %d, %Y at %H:%M') %></em>
      <strong><%= comment.title %></strong>
      <%= markdown comment.body %>
      <div>
      <%= link_to 'Edit', edit_comment_path(comment) %> |
      <%= link_to 'Destroy', comment, :method => :delete, :confirm => "Are you sure?" %> |
      <%= link_to 'Reply', new_answer_path(:comment_id => comment) %>
      </div>
      <% comment.answers.each do |answer| %>
        <div class="answer">
	  <strong><%= answer.author %></strong>
          <em>on <%= answer.created_at.strftime('%b %d, %Y at %H:%M') %>:</em>
          <%= markdown answer.body %>
          <div>
            <%= link_to 'Edit', edit_answer_path(answer) %> |
            <%= link_to 'Destroy', answer, :method => :delete, :confirm => "Are you sure?" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  </div>
<% end %>

<h3>Add your comment:</h3>
<%= render :partial => 'comments/form' %>